import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt

TABLES = Path("outputs/tables")
FIGS = Path("outputs/figs")
FIGS.mkdir(parents=True, exist_ok=True)

# This file is generated by study1_sentiment_ssp.py
mean_path = TABLES / "study1_sentiment_mean_by_year_topic_network.csv"
if not mean_path.exists():
    raise FileNotFoundError(f"Missing file: {mean_path}")

df = pd.read_csv(mean_path)

# Expect columns like: year, topic, network, mean_sentiment (name may vary slightly)
# Try to detect the sentiment column robustly.
candidate_cols = [c for c in df.columns if "mean" in c.lower() and "sent" in c.lower()]
if not candidate_cols:
    # fallback: look for a generic 'sentiment' column
    candidate_cols = [c for c in df.columns if "sentiment" in c.lower()]

if not candidate_cols:
    raise ValueError(f"Cannot find mean sentiment column in {mean_path}. Columns: {list(df.columns)}")

sent_col = candidate_cols[0]

# Pivot to get CNN and Fox side by side
pivot = df.pivot_table(
    index=["year", "topic"],
    columns="network",
    values=sent_col,
    aggfunc="mean"
).reset_index()

# Keep only rows where both networks exist
if "CNN" not in pivot.columns or "Fox" not in pivot.columns:
    raise ValueError("Pivot result missing CNN or Fox columns. Check network values in the CSV.")

pivot = pivot.dropna(subset=["CNN", "Fox"])

# Compute SSP per (year, topic)
pivot["ssp"] = (pivot["CNN"] - pivot["Fox"]).abs()

# Aggregate to a single SSP per year (mean across topics)
ssp_year = (
    pivot.groupby("year")["ssp"]
    .mean()
    .reset_index()
    .sort_values("year")
)

# Plot
plt.figure(figsize=(10, 6))
plt.plot(ssp_year["year"], ssp_year["ssp"], marker="o")
plt.title("True SSP Time Series by Year (Study 1)")
plt.xlabel("Year")
plt.ylabel("SSP (|CNN - Fox|)")
plt.tight_layout()

out_path = FIGS / "study1_ssp_time_series.png"
plt.savefig(out_path, dpi=200)
print(f"[OK] Saved {out_path}")